
export const HOT_FETCH_GAME_LIST_BEGIN = 'HOT_FETCH_GAME_LIST_BEGIN';
export const HOT_FETCH_GAME_LIST_SUCCESS = 'HOT_FETCH_GAME_LIST_SUCCESS';
export const HOT_FETCH_GAME_LIST_FAILURE = 'HOT_FETCH_GAME_LIST_FAILURE';
export const HOT_FETCH_GAME_LIST_DISMISS_ERROR = 'HOT_FETCH_GAME_LIST_DISMISS_ERROR';
